package objects;

import java.util.ArrayList;

public class Pizza {
    Integer pizzaId;   // maybe this is autogenerated
    Integer creatorId;
    String name;
    ArrayList toppings; // probably Strings, or enums, or something
    String description;
    Double rating;  // wouldn't it be fun if other people could see and rate your creation?
    Integer ratingCount;    // number of total ratings

    public Integer getPizzaId() {
        return pizzaId;
    }

    public void setPizzaId(Integer pizzaId) {
        this.pizzaId = pizzaId;
    }

    public Integer getCreatorId() {
        return creatorId;
    }

    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ArrayList getToppings() {
        return toppings;
    }

    public void setToppings(ArrayList toppings) {
        this.toppings = toppings;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getRating() {
        return rating;
    }

    public void setRating(Double rating) {
        this.rating = rating;
    }

    public Integer getRatingCount() {
        return ratingCount;
    }

    public void setRatingCount(Integer ratingCount) {
        this.ratingCount = ratingCount;
    }

    // Empty constructor needed for Jackson
    public Pizza(){}
}
